services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Data Source=/app/data/balance_projection.db"
    ports:
      - "5535:8080"
    volumes:
      - sqlite_data:/app/data

volumes:
  sqlite_data:
